Create a NumPy array representing reflectivity values measured at 3 temperatures over 4-time intervals.
Task:
1.	Create the array using NumPy.
2.	Reshape it into a 3 × 4 matrix.
3.	Extract the second column using slicing.
Reverse the order of columns.


In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.reshape(3,4)
print(b,"\n")
print("Second column: \n",b[:,1])
print("Reversed order of columns: \n",b[:,::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Second column: 
 [ 2  6 10]
Reversed order of columns: 
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


## Generate a NumPy identity array (4x4) and an eye array. Reshape a flat array of 12 elements into 3x4 and 4x3; perform transposition and flattening. Illustrate iterating over the reshaped array with code for environmental sensor data simulation.

In [1]:
import numpy as np

print("===== NUMPY MATRIX OPERATIONS DEMO =====\n")
identity_matrix = np.identity(4)
eye_matrix = np.eye(4)

print("Identity Matrix (4x4):\n", identity_matrix)
print("\nEye Matrix (4x4):\n", eye_matrix)
flat_array = np.arange(1, 13)
print("\nFlat Array (12 elements):\n", flat_array)
array_3x4 = flat_array.reshape(3, 4)
array_4x3 = flat_array.reshape(4, 3)
print("\nReshaped to 3x4:\n", array_3x4)
print("\nReshaped to 4x3:\n", array_4x3)
transpose_array = array_3x4.T
print("\nTranspose of 3x4 (4x3):\n", transpose_array)
flattened_array = array_3x4.flatten()
print("\nFlattened Array:\n", flattened_array)
print("\n===== Environmental Sensor Data Simulation =====")
sensor_data = np.array([
    [32.5, 65.2, 410, 1012],
    [30.1, 70.3, 420, 1010],
    [29.8, 75.0, 415, 1008]
])

parameters = ["Temperature (°C)", "Humidity (%)", "CO2 (ppm)", "Pressure (hPa)"]
for i, location in enumerate(sensor_data):
    print(f"\nLocation {i+1}:")
    for j, value in enumerate(location):
        print(f"  {parameters[j]}: {value}")
print("\nAll Sensor Values (Element-wise using nditer):")
for value in np.nditer(sensor_data):
    print(value, end=" ")

print("\n\n===== END OF DEMO =====")

===== NUMPY MATRIX OPERATIONS DEMO =====

Identity Matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Eye Matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Flat Array (12 elements):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Transpose of 3x4 (4x3):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

===== Environmental Sensor Data Simulation =====

Location 1:
  Temperature (°C): 32.5
  Humidity (%): 65.2
  CO2 (ppm): 410.0
  Pressure (hPa): 1012.0

Location 2:
  Temperature (°C): 30.1
  Humidity (%): 70.3
  CO2 (ppm): 420.0
  Pressure (hPa): 1010.0

Location 3:
  Temperature (°C): 29.8
  Humidity (%): 75.0
  CO2 (ppm): 415.0
  Pressure (hPa): 1008.0

All Sensor Values (Element-wise using nditer):
32.5 65.2 410.0 1012.0 30.1 70.3 420.0 1010.0 29.8 75.

## Make a sample CSV dataset into a Pandas DataFrame (e.g., sales data). Apply reindexing to add a new index, drop missing entries, select specific columns via loc/iloc, and compute summary statistics (mean, std). Explain data alignment issues resolved.