Create a NumPy array representing reflectivity values measured at 3 temperatures over 4-time intervals.
Task:
1.	Create the array using NumPy.
2.	Reshape it into a 3 × 4 matrix.
3.	Extract the second column using slicing.
Reverse the order of columns.


In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.reshape(3,4)
print(b,"\n")
print("Second column: \n",b[:,1])
print("Reversed order of columns: \n",b[:,::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Second column: 
 [ 2  6 10]
Reversed order of columns: 
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


Generate a NumPy identity array (4x4) and an eye array. Reshape a flat array of 12 elements into 3x4 and 4x3; perform transposition and flattening. Illustrate iterating over the reshaped array with code for environmental sensor data simulation.