Create a NumPy array representing reflectivity values measured at 3 temperatures over 4-time intervals.
Task:
1.	Create the array using NumPy.
2.	Reshape it into a 3 × 4 matrix.
3.	Extract the second column using slicing.
Reverse the order of columns.


In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a.reshape(3,4)
print(b,"\n")
print("Second column: \n",b[:,1])
print("Reversed order of columns: \n",b[:,::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Second column: 
 [ 2  6 10]
Reversed order of columns: 
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


## Generate a NumPy identity array (4x4) and an eye array. Reshape a flat array of 12 elements into 3x4 and 4x3; perform transposition and flattening. Illustrate iterating over the reshaped array with code for environmental sensor data simulation.

In [1]:
import numpy as np

print("===== NUMPY MATRIX OPERATIONS DEMO =====\n")
identity_matrix = np.identity(4)
eye_matrix = np.eye(4)

print("Identity Matrix (4x4):\n", identity_matrix)
print("\nEye Matrix (4x4):\n", eye_matrix)
flat_array = np.arange(1, 13)
print("\nFlat Array (12 elements):\n", flat_array)
array_3x4 = flat_array.reshape(3, 4)
array_4x3 = flat_array.reshape(4, 3)
print("\nReshaped to 3x4:\n", array_3x4)
print("\nReshaped to 4x3:\n", array_4x3)
transpose_array = array_3x4.T
print("\nTranspose of 3x4 (4x3):\n", transpose_array)
flattened_array = array_3x4.flatten()
print("\nFlattened Array:\n", flattened_array)
print("\n===== Environmental Sensor Data Simulation =====")
sensor_data = np.array([
    [32.5, 65.2, 410, 1012],
    [30.1, 70.3, 420, 1010],
    [29.8, 75.0, 415, 1008]
])

parameters = ["Temperature (°C)", "Humidity (%)", "CO2 (ppm)", "Pressure (hPa)"]
for i, location in enumerate(sensor_data):
    print(f"\nLocation {i+1}:")
    for j, value in enumerate(location):
        print(f"  {parameters[j]}: {value}")
print("\nAll Sensor Values (Element-wise using nditer):")
for value in np.nditer(sensor_data):
    print(value, end=" ")

print("\n\n===== END OF DEMO =====")

===== NUMPY MATRIX OPERATIONS DEMO =====

Identity Matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Eye Matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Flat Array (12 elements):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Transpose of 3x4 (4x3):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

===== Environmental Sensor Data Simulation =====

Location 1:
  Temperature (°C): 32.5
  Humidity (%): 65.2
  CO2 (ppm): 410.0
  Pressure (hPa): 1012.0

Location 2:
  Temperature (°C): 30.1
  Humidity (%): 70.3
  CO2 (ppm): 420.0
  Pressure (hPa): 1010.0

Location 3:
  Temperature (°C): 29.8
  Humidity (%): 75.0
  CO2 (ppm): 415.0
  Pressure (hPa): 1008.0

All Sensor Values (Element-wise using nditer):
32.5 65.2 410.0 1012.0 30.1 70.3 420.0 1010.0 29.8 75.

## Make a sample CSV dataset into a Pandas DataFrame (e.g., sales data). Apply reindexing to add a new index, drop missing entries, select specific columns via loc/iloc, and compute summary statistics (mean, std). Explain data alignment issues resolved.

In [1]:

import pandas as pd
import numpy as np
from io import StringIO

print("===== SALES DATA ANALYSIS WITH PANDAS =====\n")

csv_data = """OrderID,Product,Region,Sales,Profit
101,Laptop,North,1200,200
102,Phone,South,800,150
103,Tablet,East,,100
104,Laptop,West,1500,250
105,Phone,North,900,
"""

df = pd.read_csv(StringIO(csv_data))

print("Original DataFrame:\n")
print(df)

df_reindexed = df.reindex(range(0, 6))  # Add an extra index row
print("\nAfter Reindexing (New Empty Row Added):\n")
print(df_reindexed)

df_clean = df_reindexed.dropna()
print("\nAfter Dropping Missing Values:\n")
print(df_clean)

selected_loc = df_clean.loc[:, ["Product", "Sales"]]
print("\nSelected Columns using loc:\n")
print(selected_loc)

selected_iloc = df_clean.iloc[:, [1, 3]]
print("\nSelected Columns using iloc:\n")
print(selected_iloc)

print("\nSummary Statistics (Sales & Profit):\n")

print("Mean:\n", df_clean[["Sales", "Profit"]].mean())
print("\nStandard Deviation:\n", df_clean[["Sales", "Profit"]].std())

print("\n===== END OF ANALYSIS =====")

===== SALES DATA ANALYSIS WITH PANDAS =====

Original DataFrame:

   OrderID Product Region   Sales  Profit
0      101  Laptop  North  1200.0   200.0
1      102   Phone  South   800.0   150.0
2      103  Tablet   East     NaN   100.0
3      104  Laptop   West  1500.0   250.0
4      105   Phone  North   900.0     NaN

After Reindexing (New Empty Row Added):

   OrderID Product Region   Sales  Profit
0    101.0  Laptop  North  1200.0   200.0
1    102.0   Phone  South   800.0   150.0
2    103.0  Tablet   East     NaN   100.0
3    104.0  Laptop   West  1500.0   250.0
4    105.0   Phone  North   900.0     NaN
5      NaN     NaN    NaN     NaN     NaN

After Dropping Missing Values:

   OrderID Product Region   Sales  Profit
0    101.0  Laptop  North  1200.0   200.0
1    102.0   Phone  South   800.0   150.0
3    104.0  Laptop   West  1500.0   250.0

Selected Columns using loc:

  Product   Sales
0  Laptop  1200.0
1   Phone   800.0
3  Laptop  1500.0

Selected Columns using iloc:

  Product   

Obtain a real-world dataset related to weather or environmental sensing from an open data source or API.
Task:
1.	Load the dataset into Pandas.
2.	Display summary statistics using built-in functions.
3.	Sort the data based on one numerical column.
4.	Rank the entries based on that column.


In [2]:
import requests
import pandas as pd

print("===== REAL-WORLD WEATHER DATA ANALYSIS =====\n")

# --------------------------------------------------
# 1️⃣ Obtain Real Weather Dataset (Open-Meteo API)
# --------------------------------------------------

# Chennai Coordinates
latitude = 13.0827
longitude = 80.2707

url = (
    "https://archive-api.open-meteo.com/v1/archive?"
    f"latitude={latitude}&longitude={longitude}"
    "&start_date=2024-02-01"
    "&end_date=2024-02-07"
    "&daily=temperature_2m_max"
    "&timezone=Asia/Kolkata"
)

response = requests.get(url)
data = response.json()

# Extract daily weather data
dates = data["daily"]["time"]
max_temp = data["daily"]["temperature_2m_max"]

# Create DataFrame
df = pd.DataFrame({
    "Date": dates,
    "Max_Temperature_C": max_temp
})

print("Weather Dataset Loaded:\n")
print(df)

# --------------------------------------------------
# 2️⃣ Summary Statistics
# --------------------------------------------------
print("\nSummary Statistics:\n")
print(df.describe())

# --------------------------------------------------
# 3️⃣ Sort by Maximum Temperature
# --------------------------------------------------
df_sorted = df.sort_values(by="Max_Temperature_C", ascending=False)

print("\nSorted by Max Temperature (Descending):\n")
print(df_sorted)

# --------------------------------------------------
# 4️⃣ Rank Entries Based on Temperature
# --------------------------------------------------
df_sorted["Temperature_Rank"] = df_sorted["Max_Temperature_C"].rank(ascending=False)

print("\nRanked Dataset:\n")
print(df_sorted)

print("\n===== ANALYSIS COMPLETE =====")

===== REAL-WORLD WEATHER DATA ANALYSIS =====

Weather Dataset Loaded:

         Date  Max_Temperature_C
0  2024-02-01               29.2
1  2024-02-02               29.9
2  2024-02-03               29.8
3  2024-02-04               30.0
4  2024-02-05               29.8
5  2024-02-06               29.8
6  2024-02-07               30.3

Summary Statistics:

       Max_Temperature_C
count           7.000000
mean           29.828571
std             0.330224
min            29.200000
25%            29.800000
50%            29.800000
75%            29.950000
max            30.300000

Sorted by Max Temperature (Descending):

         Date  Max_Temperature_C
6  2024-02-07               30.3
3  2024-02-04               30.0
1  2024-02-02               29.9
4  2024-02-05               29.8
2  2024-02-03               29.8
5  2024-02-06               29.8
0  2024-02-01               29.2

Ranked Dataset:

         Date  Max_Temperature_C  Temperature_Rank
6  2024-02-07               30.3           